//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpc.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.JobAssigns = new HashSet<JobAssign>();
            this.ManHours = new HashSet<ManHour>();
        }
    
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Manager { get; set; }
        public string Shed { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<JobAssign> JobAssigns { get; set; }
        public virtual ICollection<ManHour> ManHours { get; set; }
    }
}
