//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpc.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Works = new HashSet<Work>();
        }
    
        public string JobID { get; set; }
        public string JobName { get; set; }
    
        public virtual ICollection<Work> Works { get; set; }
    }
}
